record-shop/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Album, single or EP (Extended Play).</description>
    <label>Record</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

record-shop/main/default/objects/Record__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <description>Singer, composer or band.</description>
    <label>Artist</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

record-shop/main/default/objects/Record__c/fields/Cover__c.field-meta.xml
<CustomField>
    <fullName>Cover__c</fullName>
    <description>URL to get access to the record&apos;s cover.</description>
    <label>Cover</label>
    <type>Url</type>
</CustomField>

record-shop/main/default/objects/Record__c/fields/Likes__c.field-meta.xml
<CustomField>
    <fullName>Likes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of likes for this record.</description>
    <label>Likes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

record-shop/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Users&apos; subscriptions to web push notifications.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{00000}</displayFormat>
        <label>Subscription</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

record-shop/main/default/objects/Subscription__c/fields/auth__c.field-meta.xml
<CustomField>
    <fullName>auth__c</fullName>
    <description>Authentication secret.</description>
    <label>auth</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

record-shop/main/default/objects/Subscription__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Unique endpoint associated with the push subscription.</description>
    <externalId>true</externalId>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

record-shop/main/default/objects/Subscription__c/fields/p256dh__c.field-meta.xml
<CustomField>
    <fullName>p256dh__c</fullName>
    <label>p256dh</label>
    <length>175</length>
    <maskChar>X</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

record-shop/main/default/classes/WebPushNotification_Test.cls
/**
 * @author Rémi Le Guin
 * @date 01/03/2021
 * @description Test class for the WebPushNotification class.
 */
@isTest
private class WebPushNotification_Test {

    /**
     * @description Test setup for dataset insertion.
     */
    @testSetup
    private static void setup() {
        Subscription__c[] subscriptions = new Subscription__c[] {};
        for (Integer i = 0; i < 210; i++) {
            subscriptions.add(new Subscription__c(Endpoint__c = 'http://example' + i + '.com',
                                                  p256dh__c = 'p256dhTest',
                                                  auth__c = 'authTest'));
        }
        insert subscriptions;

        Record__c[] records = new Record__c[] {};
        for (Integer i = 0; i < 210; i++) {
            records.add(new Record__c(Name = 'Song', Artist__c = 'Artist', Likes__c = 10,
                                      Year__c = 2020, Cover__c = 'http://example.com'));
        }
        insert records;
    }

    /**
     * @description Test the sendNotifications callout method.
     */
    @isTest
    private static void sendNotifications_Test() {
        PayloadComposition payloadCompositionInstance = (PayloadComposition)Type.forName('LikedRecordPayload').newInstance();
        WebPushNotificationPayload[] payloads = new WebPushNotificationPayload[] {};
        Record__c[] records = [SELECT Id, Name, Artist__c, Cover__c, Likes__c, Year__c FROM Record__c];
        for (SObject record : records) {
            payloads.add(payloadCompositionInstance.getPayload(record));
        }
        Subscription__c[] subscriptions = [SELECT Id, Endpoint__c, p256dh__c, auth__c FROM Subscription__c];

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WebPushNotification_Mock());
        HttpResponse response = WebPushNotification.sendNotifications(subscriptions, payloads);
        Test.stopTest();

        System.assertEquals(201, response.getStatusCode());
        System.assertEquals('Notifications sent', response.getBody(), 'The request body does not confirm the notification sending');
    }

    /**
     * @description Test the queueable class execution.
     */
    @isTest
    private static void execute_Test() {
        Subscription__c[] subscriptions = [SELECT Id, Endpoint__c, p256dh__c, auth__c FROM Subscription__c];
        Record__c[] records = [SELECT Id, Name, Artist__c, Cover__c, Likes__c, Year__c FROM Record__c];
        String errorMessage;

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new WebPushNotification_Mock());
        try {
            System.enqueueJob(new WebPushNotification(subscriptions, records, 'LikedRecordPayload'));
        } catch(Exception e) {
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        System.assertEquals(null, errorMessage, 'The process returned an error');
    }

}