record-shop/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Album, single or EP (Extended Play).</description>
    <label>Record</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

record-shop/main/default/objects/Record__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <description>Singer, composer or band.</description>
    <label>Artist</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

record-shop/main/default/objects/Record__c/fields/Cover__c.field-meta.xml
<CustomField>
    <fullName>Cover__c</fullName>
    <description>URL to get access to the record&apos;s cover.</description>
    <label>Cover</label>
    <type>Url</type>
</CustomField>

record-shop/main/default/objects/Record__c/fields/Likes__c.field-meta.xml
<CustomField>
    <fullName>Likes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of likes for this record.</description>
    <label>Likes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

record-shop/main/default/classes/LikedRecordPayload.cls
/**
 * @author Rémi Le Guin
 * @date 01/03/2021
 * @description Class to compose payloads when records are liked.
 */
public with sharing class LikedRecordPayload implements PayloadComposition {

    /**
     * @description Compose a WebPushNotificationPayload object ready to be serialized.
     * @param salesforceRecord A SObject record.
     * @return A WebPushNotificationPayload object instanciation.
     */
    public static WebPushNotificationPayload getPayload(SObject salesforceRecord) {
        Record__c record = (Record__c)salesforceRecord;
        WebPushNotificationPayload payload = new WebPushNotificationPayload();
        String[] titleParameters = new String[] { record.Name, record.Artist__c };
        payload.title = String.format(System.Label.LikeNotificationTitle, titleParameters);
        String[] bodyParameters = new String[] { String.valueOf((Integer)record.Likes__c) };
        payload.body = String.format(System.Label.LikeNotificationBody, bodyParameters);
        payload.icon = System.Label.RecordShopIcon;
        payload.image = record.Cover__c;
        payload.badge = System.Label.RecordShopIconMonochrome;
        return payload;
    }

}