record-shop/main/default/objects/Record__c/Record__c.object-meta.xml
<CustomObject>
    <description>Album, single or EP (Extended Play).</description>
    <label>Record</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Records</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

record-shop/main/default/objects/Record__c/fields/Artist__c.field-meta.xml
<CustomField>
    <fullName>Artist__c</fullName>
    <description>Singer, composer or band.</description>
    <label>Artist</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

record-shop/main/default/objects/Record__c/fields/Cover__c.field-meta.xml
<CustomField>
    <fullName>Cover__c</fullName>
    <description>URL to get access to the record&apos;s cover.</description>
    <label>Cover</label>
    <type>Url</type>
</CustomField>

record-shop/main/default/objects/Record__c/fields/Likes__c.field-meta.xml
<CustomField>
    <fullName>Likes__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Number of likes for this record.</description>
    <label>Likes</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

record-shop/main/default/classes/LikedRecordPayload_Test.cls
/**
 * @author Rémi Le Guin
 * @date 01/03/2021
 * @description Test for the LikedRecordPayload class.
 */
@isTest
private class LikedRecordPayload_Test {

    /**
     * @description Test the getPayload method.
     */
    @isTest
    private static void getPayload_Test() {
        Record__c record = new Record__c(Name = 'Song', Artist__c = 'Artist', Likes__c = 10,
                                         Year__c = 2020, Cover__c = 'http://example.com');

        Test.startTest();
        WebPushNotificationPayload payload = LikedRecordPayload.getPayload(record);
        Test.stopTest();

        System.assertEquals('Song from Artist has been liked!', payload.title, 'The method did not generate the right message');
        System.assertEquals('It now scores 10 likes.', payload.body, 'The method did not generate the right message');
        System.assertEquals(null, payload.iconUrl, 'The method generated an icon URL');
        System.assertEquals('http://example.com', payload.imageUrl, 'The method did not took the right URL from the record');
        System.assertEquals(null, payload.badgeUrl, 'The method generated an badge URL');
    }

}